const EErros = {
  ID_NOT_FOUND: 1,
  FIELD_OBJET_ERROR: 2,
  NOT_CONECT_MONGO: 3,
  COLLECTION_NOT_FOUND: 4,
  FILE_ERROR: 5,
  NOT_ADD_CART: 6,
  EMPTY_CART: 7,
  COULD_NOT_UPDATE: 8,
};

export default EErros;
